apiVersion: apps/v1
kind: Deployment
metadata:
  name: biohackathon_virtual_reference_collection
  labels:
    app: biohackathon_virtual_reference_collection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: biohackathon_virtual_reference_collection
  template:
    metadata:
      labels:
        app: biohackathon_virtual_reference_collection
    spec:
      containers:
        - name: biohackathon_virtual_reference_collection
          image: public.ecr.aws/dissco/biohackathon_virtual_reference_collection:latest
          ports:
            - containerPort: 3000
      restartPolicy: Always
