apiVersion: v1
kind: Service
metadata:
  name: biohackathonVirtualReferenceCollection
spec:
  selector:
    app: biohackathonVirtualReferenceCollection
  ports:
    - protocol: TCP
      port: 3000
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: biohackathonVirtualReferenceCollection-route
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`dev.dissco.tech`)
      kind: Rule
      services:
        - name: biohackathonVirtualReferenceCollection
          namespace: default
          port: 3000
