apiVersion: v1
kind: Service
metadata:
  name: biohackathon_virtual_reference_collection
spec:
  selector:
    app: biohackathon_virtual_reference_collection
  ports:
    - protocol: TCP
      port: 3000
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: biohackathon_virtual_reference_collection-route
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`dev.dissco.tech`)
      kind: Rule
      services:
        - name: biohackathon_virtual_reference_collection
          namespace: default
          port: 3000
